# Deployment do Banco de Dados
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec: 
  selector:
    matchLabels:
      app:
        postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.16
          pots:
            - conteinerPort: 5432
          env:
            - name: POSTGRES_DB
              value: fakeshop
            - name: POSTGRES_USER
              value: fakeshop
            - name: POSTGRES_PASSWORD
              value: Pg1234
---
apiVersion: v1
kind: Service
metadata: 
  - name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
# Deployment da Aplicação Web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakeshop
spec: 
  selector:
    matchLabels:
      app:
        fakeshop
  template:
    metadata:
      labels:
        app: fakeshop
    spec:
      containers:
        - name: fakeshop
          image: vitoriapena/fake-shop:v1
          pots:
            - conteinerPort: 5000
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              value: fakeshop
            - name: DB_PASSWORD
              value: Pg1234
            - name: DB_NAME
              value: fakeshop
            - name: FLASK_APP
              value: index.py
---
apiVersion: v1
kind: Service
metadata: 
  - name: fakeshop
spec:
  selector:
    app: fakeshop
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
